"""empty message

Revision ID: 09e5d8b0baec
Revises: ba7ba9950137
Create Date: 2018-09-07 22:39:54.180321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e5d8b0baec'
down_revision = 'ba7ba9950137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'dimension_two')
    op.drop_column('inventory', 'dimension_one')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('dimension_one', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('inventory', sa.Column('dimension_two', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
