"""empty message

Revision ID: 1cd17da72672
Revises: b09f8b69988e
Create Date: 2018-09-24 16:39:16.140751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd17da72672'
down_revision = 'b09f8b69988e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'price')
    # ### end Alembic commands ###
