"""empty message

Revision ID: 5f1149a2d752
Revises: 09e5d8b0baec
Create Date: 2018-09-07 22:40:25.729548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1149a2d752'
down_revision = '09e5d8b0baec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('dimension_one', sa.Integer(), nullable=False))
    op.add_column('inventory', sa.Column('dimension_two', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'dimension_two')
    op.drop_column('inventory', 'dimension_one')
    # ### end Alembic commands ###
