"""empty message

Revision ID: b09f8b69988e
Revises: 5f1149a2d752
Create Date: 2018-09-23 20:23:12.778679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09f8b69988e'
down_revision = '5f1149a2d752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po', sa.String(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po')
    )
    op.add_column('inventory_history', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inventory_history', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_history', type_='foreignkey')
    op.drop_column('inventory_history', 'order_id')
    op.drop_table('order')
    # ### end Alembic commands ###
